# Build snap for smartcampus
name: smartcampus
version: git
summary: A daemon for collecting meter data.
description: |
  A daemon for Smart Campus project.

grade: devel
confinement: devmode

parts:
  smartcampus:
    source: .
    plugin: go
    go-importpath: github.com/tig4605246/smartcampus

apps:
  smartcampus:
    command: smartcampus
